### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by morozovsk** [tony2001/ngx_http_pinba_module#13]
centos 7.4.1708
nginx-1.12.2
gcc 4.8.5

> /root/ngx_http_pinba_module/ngx_http_pinba_module.c: In function 'ngx_http_pinba_server':
> /root/ngx_http_pinba_module/ngx_http_pinba_module.c:776:16: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
>   for (i = 1; i < cf->args->nelts; i++) {
>                 ^
> /root/ngx_http_pinba_module/ngx_http_pinba_module.c: In function 'ngx_http_pinba_handler':
> /root/ngx_http_pinba_module/ngx_http_pinba_module.c:931:31: error: pointer of type 'void *' used in arithmetic [-Werror=pointer-arith]
>    server = lcf->servers->elts + lcf->servers->size * i;
>                                ^
> /root/ngx_http_pinba_module/ngx_http_pinba_module.c:1226:44: error: pointer of type 'void *' used in arithmetic [-Werror=pointer-arith]
>     ngx_pinba_socket_t **sock = socks->elts + socks->size * i;
>                                             ^
> cc1: all warnings being treated as errors
> make[1]: *** [objs/addon/ngx_http_pinba_module/ngx_http_pinba_module.o] Error 1
> make[1]: Leaving directory `/root/nginx-1.12.2'
> make: *** [build] Error 2
> 

Steps for reproduce:
```bash
git clone https://github.com/tony2001/ngx_http_pinba_module
wget http://nginx.org/download/nginx-1.12.2.tar.gz
tar zxvf nginx-1.12.2.tar.gz
cd nginx-1.12.2
./configure --add-dynamic-module=/root/ngx_http_pinba_module
make
```

After this command I have gcc 7.3.1 but still have the same error:
```bash
yum -y install centos-release-scl && yum makecache && yum -y install devtoolset-7-gcc devtoolset-7-gcc-c++ && scl enable devtoolset-7 bash
```
Update:
ubuntu 18.04
gcc 7.3.0
the same problem

**Comment by tony2001** [comment]
Fixed, thanks for the report!
