### ISSUE TITLE
cc1: warnings being treated as errors

### ISSUE THREAD

**Issue by stigout** [tony2001/ngx_http_pinba_module#7]
Hello!
The current version produces errors when compiling (with new ngx_http_pinba_module.o):

cc1: warnings being treated as errors
/usr/local/src/ngx_http_pinba_module/ngx_http_pinba_module.c: In function ‘ngx_pinba_prepare_tag’:
/usr/local/src/ngx_http_pinba_module/ngx_http_pinba_module.c:342: error: missing braces around initializer
/usr/local/src/ngx_http_pinba_module/ngx_http_pinba_module.c:342: error: (near initialization for ‘tmp_tag.name’)
/usr/local/src/ngx_http_pinba_module/ngx_http_pinba_module.c:342: error: missing initializer
/usr/local/src/ngx_http_pinba_module/ngx_http_pinba_module.c:342: error: (near initialization for ‘tmp_tag.name_len’)
/usr/local/src/ngx_http_pinba_module/ngx_http_pinba_module.c: In function ‘ngx_pinba_prepare_timer’:
/usr/local/src/ngx_http_pinba_module/ngx_http_pinba_module.c:376: error: missing initializer
/usr/local/src/ngx_http_pinba_module/ngx_http_pinba_module.c:376: error: (near initialization for ‘tmp_timer.hit_count’)
make[1]: *** [objs/addon/ngx_http_pinba_module/ngx_http_pinba_module.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/usr/local/src/nginx-1.7.11'
make: *** [build] Error 2

Version nginx 1.7.11
Previos version ngx_http_pinba_module compiled successfully

**Comment by tony2001** [comment]
Fixed, thanks for the report!

**Comment by stigout** [comment]
Problem with "prepare_timer" remained:
cc1: warnings being treated as errors
/usr/local/src/ngx_http_pinba_module/ngx_http_pinba_module.c: In function ‘ngx_pinba_prepare_timer’:
/usr/local/src/ngx_http_pinba_module/ngx_http_pinba_module.c:376: error: missing initializer
/usr/local/src/ngx_http_pinba_module/ngx_http_pinba_module.c:376: error: (near initialization for ‘tmp_timer.hit_count’)

Thank you!

**Comment by ofedoryshyn** [comment]
I have the same issue

**Comment by stigout** [comment]
ofedoryshyn, open the file "ngx_http_pinba_module/ngx_http_pinba_module.c"
and replace the line (376 line):

ngx_pinba_timer_t *prepared_timer, tmp_timer = {0};
on 
ngx_pinba_timer_t *prepared_timer, tmp_timer;

**Comment by ofedoryshyn** [comment]
Thanks. Now everything fine

**Comment by tony2001** [comment]
Or just do `git pull origin master`.
